// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	model "vt-link/backend/internal/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// MockLineRichMenuService is an autogenerated mock type for the LineRichMenuService type
type MockLineRichMenuService struct {
	mock.Mock
}

type MockLineRichMenuService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLineRichMenuService) EXPECT() *MockLineRichMenuService_Expecter {
	return &MockLineRichMenuService_Expecter{mock: &_m.Mock}
}

// CreateRichMenu provides a mock function with given fields: ctx, menu
func (_m *MockLineRichMenuService) CreateRichMenu(ctx context.Context, menu *model.RichMenu) (string, error) {
	ret := _m.Called(ctx, menu)

	if len(ret) == 0 {
		panic("no return value specified for CreateRichMenu")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RichMenu) (string, error)); ok {
		return rf(ctx, menu)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.RichMenu) string); ok {
		r0 = rf(ctx, menu)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.RichMenu) error); ok {
		r1 = rf(ctx, menu)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLineRichMenuService_CreateRichMenu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRichMenu'
type MockLineRichMenuService_CreateRichMenu_Call struct {
	*mock.Call
}

// CreateRichMenu is a helper method to define mock.On call
//   - ctx context.Context
//   - menu *model.RichMenu
func (_e *MockLineRichMenuService_Expecter) CreateRichMenu(ctx interface{}, menu interface{}) *MockLineRichMenuService_CreateRichMenu_Call {
	return &MockLineRichMenuService_CreateRichMenu_Call{Call: _e.mock.On("CreateRichMenu", ctx, menu)}
}

func (_c *MockLineRichMenuService_CreateRichMenu_Call) Run(run func(ctx context.Context, menu *model.RichMenu)) *MockLineRichMenuService_CreateRichMenu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.RichMenu))
	})
	return _c
}

func (_c *MockLineRichMenuService_CreateRichMenu_Call) Return(richMenuID string, err error) *MockLineRichMenuService_CreateRichMenu_Call {
	_c.Call.Return(richMenuID, err)
	return _c
}

func (_c *MockLineRichMenuService_CreateRichMenu_Call) RunAndReturn(run func(context.Context, *model.RichMenu) (string, error)) *MockLineRichMenuService_CreateRichMenu_Call {
	_c.Call.Return(run)
	return _c
}

// UploadImage provides a mock function with given fields: ctx, richMenuID, imageData
func (_m *MockLineRichMenuService) UploadImage(ctx context.Context, richMenuID string, imageData []byte) error {
	ret := _m.Called(ctx, richMenuID, imageData)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, richMenuID, imageData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLineRichMenuService_UploadImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadImage'
type MockLineRichMenuService_UploadImage_Call struct {
	*mock.Call
}

// UploadImage is a helper method to define mock.On call
//   - ctx context.Context
//   - richMenuID string
//   - imageData []byte
func (_e *MockLineRichMenuService_Expecter) UploadImage(ctx interface{}, richMenuID interface{}, imageData interface{}) *MockLineRichMenuService_UploadImage_Call {
	return &MockLineRichMenuService_UploadImage_Call{Call: _e.mock.On("UploadImage", ctx, richMenuID, imageData)}
}

func (_c *MockLineRichMenuService_UploadImage_Call) Run(run func(ctx context.Context, richMenuID string, imageData []byte)) *MockLineRichMenuService_UploadImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockLineRichMenuService_UploadImage_Call) Return(_a0 error) *MockLineRichMenuService_UploadImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLineRichMenuService_UploadImage_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockLineRichMenuService_UploadImage_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefault provides a mock function with given fields: ctx, richMenuID
func (_m *MockLineRichMenuService) SetDefault(ctx context.Context, richMenuID string) error {
	ret := _m.Called(ctx, richMenuID)

	if len(ret) == 0 {
		panic("no return value specified for SetDefault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, richMenuID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLineRichMenuService_SetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefault'
type MockLineRichMenuService_SetDefault_Call struct {
	*mock.Call
}

// SetDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - richMenuID string
func (_e *MockLineRichMenuService_Expecter) SetDefault(ctx interface{}, richMenuID interface{}) *MockLineRichMenuService_SetDefault_Call {
	return &MockLineRichMenuService_SetDefault_Call{Call: _e.mock.On("SetDefault", ctx, richMenuID)}
}

func (_c *MockLineRichMenuService_SetDefault_Call) Run(run func(ctx context.Context, richMenuID string)) *MockLineRichMenuService_SetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLineRichMenuService_SetDefault_Call) Return(_a0 error) *MockLineRichMenuService_SetDefault_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLineRichMenuService_SetDefault_Call) RunAndReturn(run func(context.Context, string) error) *MockLineRichMenuService_SetDefault_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRichMenu provides a mock function with given fields: ctx, richMenuID
func (_m *MockLineRichMenuService) DeleteRichMenu(ctx context.Context, richMenuID string) error {
	ret := _m.Called(ctx, richMenuID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRichMenu")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, richMenuID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLineRichMenuService_DeleteRichMenu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRichMenu'
type MockLineRichMenuService_DeleteRichMenu_Call struct {
	*mock.Call
}

// DeleteRichMenu is a helper method to define mock.On call
//   - ctx context.Context
//   - richMenuID string
func (_e *MockLineRichMenuService_Expecter) DeleteRichMenu(ctx interface{}, richMenuID interface{}) *MockLineRichMenuService_DeleteRichMenu_Call {
	return &MockLineRichMenuService_DeleteRichMenu_Call{Call: _e.mock.On("DeleteRichMenu", ctx, richMenuID)}
}

func (_c *MockLineRichMenuService_DeleteRichMenu_Call) Run(run func(ctx context.Context, richMenuID string)) *MockLineRichMenuService_DeleteRichMenu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLineRichMenuService_DeleteRichMenu_Call) Return(_a0 error) *MockLineRichMenuService_DeleteRichMenu_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLineRichMenuService_DeleteRichMenu_Call) RunAndReturn(run func(context.Context, string) error) *MockLineRichMenuService_DeleteRichMenu_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLineRichMenuService creates a new instance of MockLineRichMenuService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLineRichMenuService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLineRichMenuService {
	mock := &MockLineRichMenuService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
