// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	richmenu "vt-link/backend/internal/application/richmenu"
	model "vt-link/backend/internal/domain/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CreateRichMenu mocks base method.
func (m *MockUsecase) CreateRichMenu(ctx context.Context, input *richmenu.CreateRichMenuInput) (*model.RichMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRichMenu", ctx, input)
	ret0, _ := ret[0].(*model.RichMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRichMenu indicates an expected call of CreateRichMenu.
func (mr *MockUsecaseMockRecorder) CreateRichMenu(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRichMenu", reflect.TypeOf((*MockUsecase)(nil).CreateRichMenu), ctx, input)
}

// DeleteRichMenu mocks base method.
func (m *MockUsecase) DeleteRichMenu(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRichMenu", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRichMenu indicates an expected call of DeleteRichMenu.
func (mr *MockUsecaseMockRecorder) DeleteRichMenu(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRichMenu", reflect.TypeOf((*MockUsecase)(nil).DeleteRichMenu), ctx, id)
}

// GetRichMenu mocks base method.
func (m *MockUsecase) GetRichMenu(ctx context.Context, userID uuid.UUID) (*model.RichMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRichMenu", ctx, userID)
	ret0, _ := ret[0].(*model.RichMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRichMenu indicates an expected call of GetRichMenu.
func (mr *MockUsecaseMockRecorder) GetRichMenu(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRichMenu", reflect.TypeOf((*MockUsecase)(nil).GetRichMenu), ctx, userID)
}

// PublishToLINE mocks base method.
func (m *MockUsecase) PublishToLINE(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishToLINE", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishToLINE indicates an expected call of PublishToLINE.
func (mr *MockUsecaseMockRecorder) PublishToLINE(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishToLINE", reflect.TypeOf((*MockUsecase)(nil).PublishToLINE), ctx, id)
}

// UpdateRichMenu mocks base method.
func (m *MockUsecase) UpdateRichMenu(ctx context.Context, input *richmenu.UpdateRichMenuInput) (*model.RichMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRichMenu", ctx, input)
	ret0, _ := ret[0].(*model.RichMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRichMenu indicates an expected call of UpdateRichMenu.
func (mr *MockUsecaseMockRecorder) UpdateRichMenu(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRichMenu", reflect.TypeOf((*MockUsecase)(nil).UpdateRichMenu), ctx, input)
}
