// Code generated by MockGen. DO NOT EDIT.
// Source: interactor.go
//
// Generated by this command:
//
//	mockgen -source=interactor.go -destination=mocks/mock_interactor.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "vt-link/backend/internal/domain/model"

	gomock "go.uber.org/mock/gomock"
)

// MockLineRichMenuService is a mock of LineRichMenuService interface.
type MockLineRichMenuService struct {
	ctrl     *gomock.Controller
	recorder *MockLineRichMenuServiceMockRecorder
	isgomock struct{}
}

// MockLineRichMenuServiceMockRecorder is the mock recorder for MockLineRichMenuService.
type MockLineRichMenuServiceMockRecorder struct {
	mock *MockLineRichMenuService
}

// NewMockLineRichMenuService creates a new mock instance.
func NewMockLineRichMenuService(ctrl *gomock.Controller) *MockLineRichMenuService {
	mock := &MockLineRichMenuService{ctrl: ctrl}
	mock.recorder = &MockLineRichMenuServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLineRichMenuService) EXPECT() *MockLineRichMenuServiceMockRecorder {
	return m.recorder
}

// CreateRichMenu mocks base method.
func (m *MockLineRichMenuService) CreateRichMenu(ctx context.Context, menu *model.RichMenu) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRichMenu", ctx, menu)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRichMenu indicates an expected call of CreateRichMenu.
func (mr *MockLineRichMenuServiceMockRecorder) CreateRichMenu(ctx, menu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRichMenu", reflect.TypeOf((*MockLineRichMenuService)(nil).CreateRichMenu), ctx, menu)
}

// DeleteRichMenu mocks base method.
func (m *MockLineRichMenuService) DeleteRichMenu(ctx context.Context, richMenuID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRichMenu", ctx, richMenuID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRichMenu indicates an expected call of DeleteRichMenu.
func (mr *MockLineRichMenuServiceMockRecorder) DeleteRichMenu(ctx, richMenuID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRichMenu", reflect.TypeOf((*MockLineRichMenuService)(nil).DeleteRichMenu), ctx, richMenuID)
}

// SetDefault mocks base method.
func (m *MockLineRichMenuService) SetDefault(ctx context.Context, richMenuID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefault", ctx, richMenuID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefault indicates an expected call of SetDefault.
func (mr *MockLineRichMenuServiceMockRecorder) SetDefault(ctx, richMenuID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefault", reflect.TypeOf((*MockLineRichMenuService)(nil).SetDefault), ctx, richMenuID)
}

// UploadImage mocks base method.
func (m *MockLineRichMenuService) UploadImage(ctx context.Context, richMenuID string, imageData []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, richMenuID, imageData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockLineRichMenuServiceMockRecorder) UploadImage(ctx, richMenuID, imageData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockLineRichMenuService)(nil).UploadImage), ctx, richMenuID, imageData)
}
