extends: ["@stoplight/spectral-rulesets/oas"]

rules:
  # OpenAPI基本ルール
  info-contact: error
  info-description: error
  info-license: off
  operation-description: error
  operation-operationId: error
  operation-summary: error
  operation-tags: error
  paths-kebab-case: error

  # カスタムルール
  operation-operationId-unique: error
  operation-parameters: error

  # 緩和設定（必要に応じて）
  no-$ref-siblings: off