// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	autoreply "vt-link/backend/internal/application/autoreply"
	model "vt-link/backend/internal/domain/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// BulkUpdateRules mocks base method.
func (m *MockUsecase) BulkUpdateRules(ctx context.Context, input *autoreply.BulkUpdateInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateRules", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateRules indicates an expected call of BulkUpdateRules.
func (mr *MockUsecaseMockRecorder) BulkUpdateRules(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateRules", reflect.TypeOf((*MockUsecase)(nil).BulkUpdateRules), ctx, input)
}

// CreateRule mocks base method.
func (m *MockUsecase) CreateRule(ctx context.Context, input *autoreply.CreateRuleInput) (*model.AutoReplyRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, input)
	ret0, _ := ret[0].(*model.AutoReplyRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockUsecaseMockRecorder) CreateRule(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockUsecase)(nil).CreateRule), ctx, input)
}

// DeleteRule mocks base method.
func (m *MockUsecase) DeleteRule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockUsecaseMockRecorder) DeleteRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockUsecase)(nil).DeleteRule), ctx, id)
}

// ListRules mocks base method.
func (m *MockUsecase) ListRules(ctx context.Context, userID uuid.UUID) ([]*model.AutoReplyRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx, userID)
	ret0, _ := ret[0].([]*model.AutoReplyRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockUsecaseMockRecorder) ListRules(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockUsecase)(nil).ListRules), ctx, userID)
}

// ProcessWebhook mocks base method.
func (m *MockUsecase) ProcessWebhook(ctx context.Context, input *autoreply.WebhookInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessWebhook", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessWebhook indicates an expected call of ProcessWebhook.
func (mr *MockUsecaseMockRecorder) ProcessWebhook(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessWebhook", reflect.TypeOf((*MockUsecase)(nil).ProcessWebhook), ctx, input)
}

// UpdateRule mocks base method.
func (m *MockUsecase) UpdateRule(ctx context.Context, input *autoreply.UpdateRuleInput) (*model.AutoReplyRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", ctx, input)
	ret0, _ := ret[0].(*model.AutoReplyRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockUsecaseMockRecorder) UpdateRule(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockUsecase)(nil).UpdateRule), ctx, input)
}
