# golangci-lint configuration - minimal setup
run:
  timeout: 3m
  tests: true

linters:
  enable:
    - errcheck      # エラーチェック漏れ
    - govet         # go vetチェック
    - ineffassign   # 無駄な代入
    - staticcheck   # 静的解析
    - unused        # 未使用コード

issues:
  exclude-dirs:
    - vendor
    - mocks
  exclude-rules:
    # テストファイルでは一部緩和
    - path: _test\.go
      linters:
        - errcheck
