# golangci-lint configuration for VT-Link Backend
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []
  skip-dirs:
    - vendor
    - mocks
    - ".git"
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
    ignore: fmt:.*,io/ioutil:^Read.*

  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment # 構造体の最適化は一旦無効

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: vt-link/backend

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport

  gosec:
    excludes:
      - G104 # audit errors not checked (一部の場面では許可)
    config:
      G301: "0755"
      G302: "0644"

  revive:
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]

  misspell:
    locale: US

  unused:
    check-exported: false

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - revive
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - bodyclose
    - noctx
    - goconst

  disable:
    - deadcode  # deprecated
    - varcheck  # deprecated
    - structcheck  # deprecated
    - maligned  # deprecated
    - golint   # deprecated
    - scopelint # deprecated
    - interfacer # deprecated

issues:
  exclude-rules:
    # テストファイルでの一部ルールを無効化
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic
        - revive

    # モックファイルは除外
    - path: mocks/
      linters:
        - all

    # 生成されたファイルは除外
    - path: ".*\\.pb\\.go"
      linters:
        - all

    # 一時的に無効化するルール
    - text: "should have a package comment"
      linters:
        - revive

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error