// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	campaign "vt-link/backend/internal/application/campaign"

	mock "github.com/stretchr/testify/mock"

	model "vt-link/backend/internal/domain/model"

	uuid "github.com/google/uuid"
)

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// CreateCampaign provides a mock function with given fields: ctx, input
func (_m *MockUsecase) CreateCampaign(ctx context.Context, input *campaign.CreateCampaignInput) (*model.Campaign, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCampaign")
	}

	var r0 *model.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *campaign.CreateCampaignInput) (*model.Campaign, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *campaign.CreateCampaignInput) *model.Campaign); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *campaign.CreateCampaignInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecase_CreateCampaign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCampaign'
type MockUsecase_CreateCampaign_Call struct {
	*mock.Call
}

// CreateCampaign is a helper method to define mock.On call
//   - ctx context.Context
//   - input *campaign.CreateCampaignInput
func (_e *MockUsecase_Expecter) CreateCampaign(ctx interface{}, input interface{}) *MockUsecase_CreateCampaign_Call {
	return &MockUsecase_CreateCampaign_Call{Call: _e.mock.On("CreateCampaign", ctx, input)}
}

func (_c *MockUsecase_CreateCampaign_Call) Run(run func(ctx context.Context, input *campaign.CreateCampaignInput)) *MockUsecase_CreateCampaign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*campaign.CreateCampaignInput))
	})
	return _c
}

func (_c *MockUsecase_CreateCampaign_Call) Return(_a0 *model.Campaign, _a1 error) *MockUsecase_CreateCampaign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecase_CreateCampaign_Call) RunAndReturn(run func(context.Context, *campaign.CreateCampaignInput) (*model.Campaign, error)) *MockUsecase_CreateCampaign_Call {
	_c.Call.Return(run)
	return _c
}

// GetCampaign provides a mock function with given fields: ctx, id
func (_m *MockUsecase) GetCampaign(ctx context.Context, id uuid.UUID) (*model.Campaign, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaign")
	}

	var r0 *model.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Campaign, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Campaign); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecase_GetCampaign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCampaign'
type MockUsecase_GetCampaign_Call struct {
	*mock.Call
}

// GetCampaign is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsecase_Expecter) GetCampaign(ctx interface{}, id interface{}) *MockUsecase_GetCampaign_Call {
	return &MockUsecase_GetCampaign_Call{Call: _e.mock.On("GetCampaign", ctx, id)}
}

func (_c *MockUsecase_GetCampaign_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsecase_GetCampaign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUsecase_GetCampaign_Call) Return(_a0 *model.Campaign, _a1 error) *MockUsecase_GetCampaign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecase_GetCampaign_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Campaign, error)) *MockUsecase_GetCampaign_Call {
	_c.Call.Return(run)
	return _c
}

// ListCampaigns provides a mock function with given fields: ctx, input
func (_m *MockUsecase) ListCampaigns(ctx context.Context, input *campaign.ListCampaignsInput) ([]*model.Campaign, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListCampaigns")
	}

	var r0 []*model.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *campaign.ListCampaignsInput) ([]*model.Campaign, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *campaign.ListCampaignsInput) []*model.Campaign); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *campaign.ListCampaignsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecase_ListCampaigns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCampaigns'
type MockUsecase_ListCampaigns_Call struct {
	*mock.Call
}

// ListCampaigns is a helper method to define mock.On call
//   - ctx context.Context
//   - input *campaign.ListCampaignsInput
func (_e *MockUsecase_Expecter) ListCampaigns(ctx interface{}, input interface{}) *MockUsecase_ListCampaigns_Call {
	return &MockUsecase_ListCampaigns_Call{Call: _e.mock.On("ListCampaigns", ctx, input)}
}

func (_c *MockUsecase_ListCampaigns_Call) Run(run func(ctx context.Context, input *campaign.ListCampaignsInput)) *MockUsecase_ListCampaigns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*campaign.ListCampaignsInput))
	})
	return _c
}

func (_c *MockUsecase_ListCampaigns_Call) Return(_a0 []*model.Campaign, _a1 error) *MockUsecase_ListCampaigns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecase_ListCampaigns_Call) RunAndReturn(run func(context.Context, *campaign.ListCampaignsInput) ([]*model.Campaign, error)) *MockUsecase_ListCampaigns_Call {
	_c.Call.Return(run)
	return _c
}

// RunScheduler provides a mock function with given fields: ctx, input
func (_m *MockUsecase) RunScheduler(ctx context.Context, input *campaign.SchedulerInput) (int, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RunScheduler")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *campaign.SchedulerInput) (int, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *campaign.SchedulerInput) int); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *campaign.SchedulerInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecase_RunScheduler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunScheduler'
type MockUsecase_RunScheduler_Call struct {
	*mock.Call
}

// RunScheduler is a helper method to define mock.On call
//   - ctx context.Context
//   - input *campaign.SchedulerInput
func (_e *MockUsecase_Expecter) RunScheduler(ctx interface{}, input interface{}) *MockUsecase_RunScheduler_Call {
	return &MockUsecase_RunScheduler_Call{Call: _e.mock.On("RunScheduler", ctx, input)}
}

func (_c *MockUsecase_RunScheduler_Call) Run(run func(ctx context.Context, input *campaign.SchedulerInput)) *MockUsecase_RunScheduler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*campaign.SchedulerInput))
	})
	return _c
}

func (_c *MockUsecase_RunScheduler_Call) Return(_a0 int, _a1 error) *MockUsecase_RunScheduler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecase_RunScheduler_Call) RunAndReturn(run func(context.Context, *campaign.SchedulerInput) (int, error)) *MockUsecase_RunScheduler_Call {
	_c.Call.Return(run)
	return _c
}

// SendCampaign provides a mock function with given fields: ctx, input
func (_m *MockUsecase) SendCampaign(ctx context.Context, input *campaign.SendCampaignInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SendCampaign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *campaign.SendCampaignInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecase_SendCampaign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCampaign'
type MockUsecase_SendCampaign_Call struct {
	*mock.Call
}

// SendCampaign is a helper method to define mock.On call
//   - ctx context.Context
//   - input *campaign.SendCampaignInput
func (_e *MockUsecase_Expecter) SendCampaign(ctx interface{}, input interface{}) *MockUsecase_SendCampaign_Call {
	return &MockUsecase_SendCampaign_Call{Call: _e.mock.On("SendCampaign", ctx, input)}
}

func (_c *MockUsecase_SendCampaign_Call) Run(run func(ctx context.Context, input *campaign.SendCampaignInput)) *MockUsecase_SendCampaign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*campaign.SendCampaignInput))
	})
	return _c
}

func (_c *MockUsecase_SendCampaign_Call) Return(_a0 error) *MockUsecase_SendCampaign_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecase_SendCampaign_Call) RunAndReturn(run func(context.Context, *campaign.SendCampaignInput) error) *MockUsecase_SendCampaign_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
