// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	audience "vt-link/backend/internal/application/audience"
	model "vt-link/backend/internal/domain/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// BlockFan mocks base method.
func (m *MockUsecase) BlockFan(ctx context.Context, input *audience.BlockFanInput) (*model.Fan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockFan", ctx, input)
	ret0, _ := ret[0].(*model.Fan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockFan indicates an expected call of BlockFan.
func (mr *MockUsecaseMockRecorder) BlockFan(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockFan", reflect.TypeOf((*MockUsecase)(nil).BlockFan), ctx, input)
}

// DeleteFan mocks base method.
func (m *MockUsecase) DeleteFan(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFan", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFan indicates an expected call of DeleteFan.
func (mr *MockUsecaseMockRecorder) DeleteFan(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFan", reflect.TypeOf((*MockUsecase)(nil).DeleteFan), ctx, id)
}

// GetFan mocks base method.
func (m *MockUsecase) GetFan(ctx context.Context, id uuid.UUID) (*model.Fan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFan", ctx, id)
	ret0, _ := ret[0].(*model.Fan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFan indicates an expected call of GetFan.
func (mr *MockUsecaseMockRecorder) GetFan(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFan", reflect.TypeOf((*MockUsecase)(nil).GetFan), ctx, id)
}

// GetSegments mocks base method.
func (m *MockUsecase) GetSegments(ctx context.Context, userID uuid.UUID) ([]*model.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegments", ctx, userID)
	ret0, _ := ret[0].([]*model.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSegments indicates an expected call of GetSegments.
func (mr *MockUsecaseMockRecorder) GetSegments(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegments", reflect.TypeOf((*MockUsecase)(nil).GetSegments), ctx, userID)
}

// GetStats mocks base method.
func (m *MockUsecase) GetStats(ctx context.Context, userID uuid.UUID) (*model.AudienceStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, userID)
	ret0, _ := ret[0].(*model.AudienceStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockUsecaseMockRecorder) GetStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockUsecase)(nil).GetStats), ctx, userID)
}

// ListFans mocks base method.
func (m *MockUsecase) ListFans(ctx context.Context, input *audience.ListFansInput) (*audience.FanListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFans", ctx, input)
	ret0, _ := ret[0].(*audience.FanListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFans indicates an expected call of ListFans.
func (mr *MockUsecaseMockRecorder) ListFans(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFans", reflect.TypeOf((*MockUsecase)(nil).ListFans), ctx, input)
}

// UnblockFan mocks base method.
func (m *MockUsecase) UnblockFan(ctx context.Context, input *audience.BlockFanInput) (*model.Fan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnblockFan", ctx, input)
	ret0, _ := ret[0].(*model.Fan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnblockFan indicates an expected call of UnblockFan.
func (mr *MockUsecaseMockRecorder) UnblockFan(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnblockFan", reflect.TypeOf((*MockUsecase)(nil).UnblockFan), ctx, input)
}

// UpdateFanTags mocks base method.
func (m *MockUsecase) UpdateFanTags(ctx context.Context, input *audience.UpdateFanTagsInput) (*model.Fan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFanTags", ctx, input)
	ret0, _ := ret[0].(*model.Fan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFanTags indicates an expected call of UpdateFanTags.
func (mr *MockUsecaseMockRecorder) UpdateFanTags(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFanTags", reflect.TypeOf((*MockUsecase)(nil).UpdateFanTags), ctx, input)
}
