// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	history "vt-link/backend/internal/application/history"
	model "vt-link/backend/internal/domain/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockUsecase) GetHistory(ctx context.Context, id uuid.UUID) (*model.MessageHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, id)
	ret0, _ := ret[0].(*model.MessageHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockUsecaseMockRecorder) GetHistory(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockUsecase)(nil).GetHistory), ctx, id)
}

// GetStats mocks base method.
func (m *MockUsecase) GetStats(ctx context.Context, userID uuid.UUID) (*model.HistoryStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, userID)
	ret0, _ := ret[0].(*model.HistoryStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockUsecaseMockRecorder) GetStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockUsecase)(nil).GetStats), ctx, userID)
}

// ListHistory mocks base method.
func (m *MockUsecase) ListHistory(ctx context.Context, input *history.ListHistoryInput) ([]*model.MessageHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHistory", ctx, input)
	ret0, _ := ret[0].([]*model.MessageHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHistory indicates an expected call of ListHistory.
func (mr *MockUsecaseMockRecorder) ListHistory(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHistory", reflect.TypeOf((*MockUsecase)(nil).ListHistory), ctx, input)
}
