// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPusher is an autogenerated mock type for the Pusher type
type MockPusher struct {
	mock.Mock
}

type MockPusher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPusher) EXPECT() *MockPusher_Expecter {
	return &MockPusher_Expecter{mock: &_m.Mock}
}

// PushMessage provides a mock function with given fields: ctx, title, body
func (_m *MockPusher) PushMessage(ctx context.Context, title string, body string) error {
	ret := _m.Called(ctx, title, body)

	if len(ret) == 0 {
		panic("no return value specified for PushMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, title, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPusher_PushMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushMessage'
type MockPusher_PushMessage_Call struct {
	*mock.Call
}

// PushMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - body string
func (_e *MockPusher_Expecter) PushMessage(ctx interface{}, title interface{}, body interface{}) *MockPusher_PushMessage_Call {
	return &MockPusher_PushMessage_Call{Call: _e.mock.On("PushMessage", ctx, title, body)}
}

func (_c *MockPusher_PushMessage_Call) Run(run func(ctx context.Context, title string, body string)) *MockPusher_PushMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPusher_PushMessage_Call) Return(_a0 error) *MockPusher_PushMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPusher_PushMessage_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPusher_PushMessage_Call {
	_c.Call.Return(run)
	return _c
}

// PushText provides a mock function with given fields: ctx, text
func (_m *MockPusher) PushText(ctx context.Context, text string) error {
	ret := _m.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for PushText")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPusher_PushText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushText'
type MockPusher_PushText_Call struct {
	*mock.Call
}

// PushText is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockPusher_Expecter) PushText(ctx interface{}, text interface{}) *MockPusher_PushText_Call {
	return &MockPusher_PushText_Call{Call: _e.mock.On("PushText", ctx, text)}
}

func (_c *MockPusher_PushText_Call) Run(run func(ctx context.Context, text string)) *MockPusher_PushText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPusher_PushText_Call) Return(_a0 error) *MockPusher_PushText_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPusher_PushText_Call) RunAndReturn(run func(context.Context, string) error) *MockPusher_PushText_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPusher creates a new instance of MockPusher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPusher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPusher {
	mock := &MockPusher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
