// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLineReplier is an autogenerated mock type for the LineReplier type
type MockLineReplier struct {
	mock.Mock
}

type MockLineReplier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLineReplier) EXPECT() *MockLineReplier_Expecter {
	return &MockLineReplier_Expecter{mock: &_m.Mock}
}

// Reply provides a mock function with given fields: ctx, replyToken, text
func (_m *MockLineReplier) Reply(ctx context.Context, replyToken string, text string) error {
	ret := _m.Called(ctx, replyToken, text)

	if len(ret) == 0 {
		panic("no return value specified for Reply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, replyToken, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLineReplier_Reply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reply'
type MockLineReplier_Reply_Call struct {
	*mock.Call
}

// Reply is a helper method to define mock.On call
//   - ctx context.Context
//   - replyToken string
//   - text string
func (_e *MockLineReplier_Expecter) Reply(ctx interface{}, replyToken interface{}, text interface{}) *MockLineReplier_Reply_Call {
	return &MockLineReplier_Reply_Call{Call: _e.mock.On("Reply", ctx, replyToken, text)}
}

func (_c *MockLineReplier_Reply_Call) Run(run func(ctx context.Context, replyToken string, text string)) *MockLineReplier_Reply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockLineReplier_Reply_Call) Return(_a0 error) *MockLineReplier_Reply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLineReplier_Reply_Call) RunAndReturn(run func(context.Context, string, string) error) *MockLineReplier_Reply_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLineReplier creates a new instance of MockLineReplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLineReplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLineReplier {
	mock := &MockLineReplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
