/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * キャンペーン一覧取得
         * @description キャンペーン一覧を取得
         */
        get: {
            parameters: {
                query?: {
                    /** @description ページ番号 */
                    page?: number;
                    /** @description 1ページあたりの件数 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description キャンペーン一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            data: {
                                /**
                                 * Format: uuid
                                 * @description キャンペーンID
                                 * @example 550e8400-e29b-41d4-a716-446655440000
                                 */
                                id: string;
                                /**
                                 * @description キャンペーンタイトル
                                 * @example 新商品リリース記念キャンペーン
                                 */
                                title: string;
                                /**
                                 * @description キャンペーン本文
                                 * @example 新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！
                                 */
                                body: string;
                                /**
                                 * Format: uri
                                 * @description 画像URL
                                 * @example https://example.com/image.jpg
                                 */
                                imageUrl: string | null;
                                /**
                                 * Format: date-time
                                 * @description 配信予定日時 (ISO 8601)
                                 * @example 2025-01-15T10:00:00Z
                                 */
                                scheduledAt: string | null;
                                /**
                                 * Format: date-time
                                 * @description 配信日時 (ISO 8601)
                                 * @example 2025-01-15T10:00:00Z
                                 */
                                sentAt: string | null;
                                /**
                                 * @description キャンペーンのステータス
                                 * @example draft
                                 * @enum {string}
                                 */
                                status: "draft" | "scheduled" | "sent" | "failed";
                                /**
                                 * Format: date-time
                                 * @description 作成日時 (ISO 8601)
                                 * @example 2025-01-10T09:00:00Z
                                 */
                                createdAt: string;
                                /**
                                 * Format: date-time
                                 * @description 更新日時 (ISO 8601)
                                 * @example 2025-01-10T09:00:00Z
                                 */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * キャンペーン作成
         * @description キャンペーンを作成
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description 作成されたキャンペーン */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            /**
                             * @description キャンペーン情報
                             * @example {
                             *       "id": "550e8400-e29b-41d4-a716-446655440000",
                             *       "title": "新商品リリース記念キャンペーン",
                             *       "body": "新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！",
                             *       "imageUrl": "https://example.com/image.jpg",
                             *       "scheduledAt": "2025-01-15T10:00:00Z",
                             *       "sentAt": null,
                             *       "status": "scheduled",
                             *       "createdAt": "2025-01-10T09:00:00Z",
                             *       "updatedAt": "2025-01-10T09:00:00Z"
                             *     }
                             */
                            data: {
                                /**
                                 * Format: uuid
                                 * @description キャンペーンID
                                 * @example 550e8400-e29b-41d4-a716-446655440000
                                 */
                                id: string;
                                /**
                                 * @description キャンペーンタイトル
                                 * @example 新商品リリース記念キャンペーン
                                 */
                                title: string;
                                /**
                                 * @description キャンペーン本文
                                 * @example 新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！
                                 */
                                body: string;
                                /**
                                 * Format: uri
                                 * @description 画像URL
                                 * @example https://example.com/image.jpg
                                 */
                                imageUrl: string | null;
                                /**
                                 * Format: date-time
                                 * @description 配信予定日時 (ISO 8601)
                                 * @example 2025-01-15T10:00:00Z
                                 */
                                scheduledAt: string | null;
                                /**
                                 * Format: date-time
                                 * @description 配信日時 (ISO 8601)
                                 * @example 2025-01-15T10:00:00Z
                                 */
                                sentAt: string | null;
                                /**
                                 * @description キャンペーンのステータス
                                 * @example draft
                                 * @enum {string}
                                 */
                                status: "draft" | "scheduled" | "sent" | "failed";
                                /**
                                 * Format: date-time
                                 * @description 作成日時 (ISO 8601)
                                 * @example 2025-01-10T09:00:00Z
                                 */
                                createdAt: string;
                                /**
                                 * Format: date-time
                                 * @description 更新日時 (ISO 8601)
                                 * @example 2025-01-10T09:00:00Z
                                 */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * キャンペーン詳細取得
         * @description キャンペーン詳細を取得
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description キャンペーンID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description キャンペーン詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            /**
                             * @description キャンペーン情報
                             * @example {
                             *       "id": "550e8400-e29b-41d4-a716-446655440000",
                             *       "title": "新商品リリース記念キャンペーン",
                             *       "body": "新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！",
                             *       "imageUrl": "https://example.com/image.jpg",
                             *       "scheduledAt": "2025-01-15T10:00:00Z",
                             *       "sentAt": null,
                             *       "status": "scheduled",
                             *       "createdAt": "2025-01-10T09:00:00Z",
                             *       "updatedAt": "2025-01-10T09:00:00Z"
                             *     }
                             */
                            data: {
                                /**
                                 * Format: uuid
                                 * @description キャンペーンID
                                 * @example 550e8400-e29b-41d4-a716-446655440000
                                 */
                                id: string;
                                /**
                                 * @description キャンペーンタイトル
                                 * @example 新商品リリース記念キャンペーン
                                 */
                                title: string;
                                /**
                                 * @description キャンペーン本文
                                 * @example 新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！
                                 */
                                body: string;
                                /**
                                 * Format: uri
                                 * @description 画像URL
                                 * @example https://example.com/image.jpg
                                 */
                                imageUrl: string | null;
                                /**
                                 * Format: date-time
                                 * @description 配信予定日時 (ISO 8601)
                                 * @example 2025-01-15T10:00:00Z
                                 */
                                scheduledAt: string | null;
                                /**
                                 * Format: date-time
                                 * @description 配信日時 (ISO 8601)
                                 * @example 2025-01-15T10:00:00Z
                                 */
                                sentAt: string | null;
                                /**
                                 * @description キャンペーンのステータス
                                 * @example draft
                                 * @enum {string}
                                 */
                                status: "draft" | "scheduled" | "sent" | "failed";
                                /**
                                 * Format: date-time
                                 * @description 作成日時 (ISO 8601)
                                 * @example 2025-01-10T09:00:00Z
                                 */
                                createdAt: string;
                                /**
                                 * Format: date-time
                                 * @description 更新日時 (ISO 8601)
                                 * @example 2025-01-10T09:00:00Z
                                 */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description キャンペーンが見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        /**
         * キャンペーン更新
         * @description キャンペーンを更新
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description キャンペーンID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description 更新されたキャンペーン */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            /**
                             * @description キャンペーン情報
                             * @example {
                             *       "id": "550e8400-e29b-41d4-a716-446655440000",
                             *       "title": "新商品リリース記念キャンペーン",
                             *       "body": "新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！",
                             *       "imageUrl": "https://example.com/image.jpg",
                             *       "scheduledAt": "2025-01-15T10:00:00Z",
                             *       "sentAt": null,
                             *       "status": "scheduled",
                             *       "createdAt": "2025-01-10T09:00:00Z",
                             *       "updatedAt": "2025-01-10T09:00:00Z"
                             *     }
                             */
                            data: {
                                /**
                                 * Format: uuid
                                 * @description キャンペーンID
                                 * @example 550e8400-e29b-41d4-a716-446655440000
                                 */
                                id: string;
                                /**
                                 * @description キャンペーンタイトル
                                 * @example 新商品リリース記念キャンペーン
                                 */
                                title: string;
                                /**
                                 * @description キャンペーン本文
                                 * @example 新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！
                                 */
                                body: string;
                                /**
                                 * Format: uri
                                 * @description 画像URL
                                 * @example https://example.com/image.jpg
                                 */
                                imageUrl: string | null;
                                /**
                                 * Format: date-time
                                 * @description 配信予定日時 (ISO 8601)
                                 * @example 2025-01-15T10:00:00Z
                                 */
                                scheduledAt: string | null;
                                /**
                                 * Format: date-time
                                 * @description 配信日時 (ISO 8601)
                                 * @example 2025-01-15T10:00:00Z
                                 */
                                sentAt: string | null;
                                /**
                                 * @description キャンペーンのステータス
                                 * @example draft
                                 * @enum {string}
                                 */
                                status: "draft" | "scheduled" | "sent" | "failed";
                                /**
                                 * Format: date-time
                                 * @description 作成日時 (ISO 8601)
                                 * @example 2025-01-10T09:00:00Z
                                 */
                                createdAt: string;
                                /**
                                 * Format: date-time
                                 * @description 更新日時 (ISO 8601)
                                 * @example 2025-01-10T09:00:00Z
                                 */
                                updatedAt: string;
                            };
                        };
                    };
                };
                /** @description キャンペーンが見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * キャンペーン削除
         * @description キャンペーンを削除
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description キャンペーンID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                            message?: string;
                        };
                    };
                };
                /** @description キャンペーンが見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ファン一覧取得
         * @description ファン一覧を取得
         */
        get: {
            parameters: {
                query?: {
                    /** @description ページ番号 */
                    page?: number;
                    /** @description 1ページあたりの件数 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ファン一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            data: {
                                /**
                                 * Format: uuid
                                 * @description ファンID
                                 * @example 660e8400-e29b-41d4-a716-446655440000
                                 */
                                id: string;
                                /**
                                 * @description LINE ユーザーID
                                 * @example U1234567890abcdef1234567890abcdef
                                 */
                                lineUserId: string;
                                /**
                                 * @description 表示名
                                 * @example ファン太郎
                                 */
                                displayName: string | null;
                                /**
                                 * Format: uri
                                 * @description プロフィール画像URL
                                 * @example https://profile.line-scdn.net/...
                                 */
                                pictureUrl: string | null;
                                /**
                                 * Format: date-time
                                 * @description フォロー日時 (ISO 8601)
                                 * @example 2025-01-01T00:00:00Z
                                 */
                                followedAt: string;
                                /**
                                 * Format: date-time
                                 * @description 最終インタラクション日時 (ISO 8601)
                                 * @example 2025-01-10T15:30:00Z
                                 */
                                lastInteractionAt: string | null;
                                /**
                                 * @description ブロック状態
                                 * @default false
                                 * @example false
                                 */
                                isBlocked: boolean;
                                /**
                                 * @description ファンタグ
                                 * @example [
                                 *       "VIP",
                                 *       "アクティブ"
                                 *     ]
                                 */
                                tags: string[];
                            }[];
                            pagination: {
                                total: number;
                                page: number;
                                limit: number;
                                totalPages: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ファン詳細取得
         * @description ファン詳細を取得
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ファンID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ファン詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            /** @description ファン情報 */
                            data: {
                                /**
                                 * Format: uuid
                                 * @description ファンID
                                 * @example 660e8400-e29b-41d4-a716-446655440000
                                 */
                                id: string;
                                /**
                                 * @description LINE ユーザーID
                                 * @example U1234567890abcdef1234567890abcdef
                                 */
                                lineUserId: string;
                                /**
                                 * @description 表示名
                                 * @example ファン太郎
                                 */
                                displayName: string | null;
                                /**
                                 * Format: uri
                                 * @description プロフィール画像URL
                                 * @example https://profile.line-scdn.net/...
                                 */
                                pictureUrl: string | null;
                                /**
                                 * Format: date-time
                                 * @description フォロー日時 (ISO 8601)
                                 * @example 2025-01-01T00:00:00Z
                                 */
                                followedAt: string;
                                /**
                                 * Format: date-time
                                 * @description 最終インタラクション日時 (ISO 8601)
                                 * @example 2025-01-10T15:30:00Z
                                 */
                                lastInteractionAt: string | null;
                                /**
                                 * @description ブロック状態
                                 * @default false
                                 * @example false
                                 */
                                isBlocked: boolean;
                                /**
                                 * @description ファンタグ
                                 * @example [
                                 *       "VIP",
                                 *       "アクティブ"
                                 *     ]
                                 */
                                tags: string[];
                            };
                        };
                    };
                };
                /** @description ファンが見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: false;
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description キャンペーン情報
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440000",
         *       "title": "新商品リリース記念キャンペーン",
         *       "body": "新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！",
         *       "imageUrl": "https://example.com/image.jpg",
         *       "scheduledAt": "2025-01-15T10:00:00Z",
         *       "sentAt": null,
         *       "status": "scheduled",
         *       "createdAt": "2025-01-10T09:00:00Z",
         *       "updatedAt": "2025-01-10T09:00:00Z"
         *     }
         */
        Campaign: {
            /**
             * Format: uuid
             * @description キャンペーンID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description キャンペーンタイトル
             * @example 新商品リリース記念キャンペーン
             */
            title: string;
            /**
             * @description キャンペーン本文
             * @example 新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！
             */
            body: string;
            /**
             * Format: uri
             * @description 画像URL
             * @example https://example.com/image.jpg
             */
            imageUrl: string | null;
            /**
             * Format: date-time
             * @description 配信予定日時 (ISO 8601)
             * @example 2025-01-15T10:00:00Z
             */
            scheduledAt: string | null;
            /**
             * Format: date-time
             * @description 配信日時 (ISO 8601)
             * @example 2025-01-15T10:00:00Z
             */
            sentAt: string | null;
            /**
             * @description キャンペーンのステータス
             * @example draft
             * @enum {string}
             */
            status: "draft" | "scheduled" | "sent" | "failed";
            /**
             * Format: date-time
             * @description 作成日時 (ISO 8601)
             * @example 2025-01-10T09:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新日時 (ISO 8601)
             * @example 2025-01-10T09:00:00Z
             */
            updatedAt: string;
        };
        /** @description キャンペーン作成リクエスト */
        CreateCampaignRequest: {
            title: string;
            body: string;
            /** Format: uri */
            imageUrl?: string;
            /** Format: date-time */
            scheduledAt?: string;
            /**
             * @default draft
             * @enum {string}
             */
            status: "draft" | "scheduled";
        };
        /** @description キャンペーン更新リクエスト */
        UpdateCampaignRequest: {
            title?: string;
            body?: string;
            /** Format: uri */
            imageUrl?: string;
            /** Format: date-time */
            scheduledAt?: string;
            /**
             * @default draft
             * @enum {string}
             */
            status: "draft" | "scheduled";
        };
        /** @description キャンペーン一覧レスポンス */
        CampaignListResponse: {
            ok: boolean;
            data: {
                /**
                 * Format: uuid
                 * @description キャンペーンID
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
                /**
                 * @description キャンペーンタイトル
                 * @example 新商品リリース記念キャンペーン
                 */
                title: string;
                /**
                 * @description キャンペーン本文
                 * @example 新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！
                 */
                body: string;
                /**
                 * Format: uri
                 * @description 画像URL
                 * @example https://example.com/image.jpg
                 */
                imageUrl: string | null;
                /**
                 * Format: date-time
                 * @description 配信予定日時 (ISO 8601)
                 * @example 2025-01-15T10:00:00Z
                 */
                scheduledAt: string | null;
                /**
                 * Format: date-time
                 * @description 配信日時 (ISO 8601)
                 * @example 2025-01-15T10:00:00Z
                 */
                sentAt: string | null;
                /**
                 * @description キャンペーンのステータス
                 * @example draft
                 * @enum {string}
                 */
                status: "draft" | "scheduled" | "sent" | "failed";
                /**
                 * Format: date-time
                 * @description 作成日時 (ISO 8601)
                 * @example 2025-01-10T09:00:00Z
                 */
                createdAt: string;
                /**
                 * Format: date-time
                 * @description 更新日時 (ISO 8601)
                 * @example 2025-01-10T09:00:00Z
                 */
                updatedAt: string;
            }[];
        };
        /** @description キャンペーンレスポンス */
        CampaignResponse: {
            ok: boolean;
            /**
             * @description キャンペーン情報
             * @example {
             *       "id": "550e8400-e29b-41d4-a716-446655440000",
             *       "title": "新商品リリース記念キャンペーン",
             *       "body": "新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！",
             *       "imageUrl": "https://example.com/image.jpg",
             *       "scheduledAt": "2025-01-15T10:00:00Z",
             *       "sentAt": null,
             *       "status": "scheduled",
             *       "createdAt": "2025-01-10T09:00:00Z",
             *       "updatedAt": "2025-01-10T09:00:00Z"
             *     }
             */
            data: {
                /**
                 * Format: uuid
                 * @description キャンペーンID
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
                /**
                 * @description キャンペーンタイトル
                 * @example 新商品リリース記念キャンペーン
                 */
                title: string;
                /**
                 * @description キャンペーン本文
                 * @example 新商品のリリースを記念して、先着100名様に限定グッズをプレゼント！
                 */
                body: string;
                /**
                 * Format: uri
                 * @description 画像URL
                 * @example https://example.com/image.jpg
                 */
                imageUrl: string | null;
                /**
                 * Format: date-time
                 * @description 配信予定日時 (ISO 8601)
                 * @example 2025-01-15T10:00:00Z
                 */
                scheduledAt: string | null;
                /**
                 * Format: date-time
                 * @description 配信日時 (ISO 8601)
                 * @example 2025-01-15T10:00:00Z
                 */
                sentAt: string | null;
                /**
                 * @description キャンペーンのステータス
                 * @example draft
                 * @enum {string}
                 */
                status: "draft" | "scheduled" | "sent" | "failed";
                /**
                 * Format: date-time
                 * @description 作成日時 (ISO 8601)
                 * @example 2025-01-10T09:00:00Z
                 */
                createdAt: string;
                /**
                 * Format: date-time
                 * @description 更新日時 (ISO 8601)
                 * @example 2025-01-10T09:00:00Z
                 */
                updatedAt: string;
            };
        };
        /** @description ファン情報 */
        Fan: {
            /**
             * Format: uuid
             * @description ファンID
             * @example 660e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description LINE ユーザーID
             * @example U1234567890abcdef1234567890abcdef
             */
            lineUserId: string;
            /**
             * @description 表示名
             * @example ファン太郎
             */
            displayName: string | null;
            /**
             * Format: uri
             * @description プロフィール画像URL
             * @example https://profile.line-scdn.net/...
             */
            pictureUrl: string | null;
            /**
             * Format: date-time
             * @description フォロー日時 (ISO 8601)
             * @example 2025-01-01T00:00:00Z
             */
            followedAt: string;
            /**
             * Format: date-time
             * @description 最終インタラクション日時 (ISO 8601)
             * @example 2025-01-10T15:30:00Z
             */
            lastInteractionAt: string | null;
            /**
             * @description ブロック状態
             * @default false
             * @example false
             */
            isBlocked: boolean;
            /**
             * @description ファンタグ
             * @example [
             *       "VIP",
             *       "アクティブ"
             *     ]
             */
            tags: string[];
        };
        /** @description ファン一覧レスポンス */
        FanListResponse: {
            ok: boolean;
            data: {
                /**
                 * Format: uuid
                 * @description ファンID
                 * @example 660e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
                /**
                 * @description LINE ユーザーID
                 * @example U1234567890abcdef1234567890abcdef
                 */
                lineUserId: string;
                /**
                 * @description 表示名
                 * @example ファン太郎
                 */
                displayName: string | null;
                /**
                 * Format: uri
                 * @description プロフィール画像URL
                 * @example https://profile.line-scdn.net/...
                 */
                pictureUrl: string | null;
                /**
                 * Format: date-time
                 * @description フォロー日時 (ISO 8601)
                 * @example 2025-01-01T00:00:00Z
                 */
                followedAt: string;
                /**
                 * Format: date-time
                 * @description 最終インタラクション日時 (ISO 8601)
                 * @example 2025-01-10T15:30:00Z
                 */
                lastInteractionAt: string | null;
                /**
                 * @description ブロック状態
                 * @default false
                 * @example false
                 */
                isBlocked: boolean;
                /**
                 * @description ファンタグ
                 * @example [
                 *       "VIP",
                 *       "アクティブ"
                 *     ]
                 */
                tags: string[];
            }[];
            pagination: {
                total: number;
                page: number;
                limit: number;
                totalPages: number;
            };
        };
        /** @description ファンレスポンス */
        FanResponse: {
            ok: boolean;
            /** @description ファン情報 */
            data: {
                /**
                 * Format: uuid
                 * @description ファンID
                 * @example 660e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
                /**
                 * @description LINE ユーザーID
                 * @example U1234567890abcdef1234567890abcdef
                 */
                lineUserId: string;
                /**
                 * @description 表示名
                 * @example ファン太郎
                 */
                displayName: string | null;
                /**
                 * Format: uri
                 * @description プロフィール画像URL
                 * @example https://profile.line-scdn.net/...
                 */
                pictureUrl: string | null;
                /**
                 * Format: date-time
                 * @description フォロー日時 (ISO 8601)
                 * @example 2025-01-01T00:00:00Z
                 */
                followedAt: string;
                /**
                 * Format: date-time
                 * @description 最終インタラクション日時 (ISO 8601)
                 * @example 2025-01-10T15:30:00Z
                 */
                lastInteractionAt: string | null;
                /**
                 * @description ブロック状態
                 * @default false
                 * @example false
                 */
                isBlocked: boolean;
                /**
                 * @description ファンタグ
                 * @example [
                 *       "VIP",
                 *       "アクティブ"
                 *     ]
                 */
                tags: string[];
            };
        };
        /** @description APIエラーレスポンス */
        ApiError: {
            /** @enum {boolean} */
            ok: false;
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @description API成功レスポンス */
        ApiSuccess: {
            /** @enum {boolean} */
            ok: true;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
