// Code generated by mockery v2.53.5. DO NOT EDIT.

package repository

import (
	context "context"
	model "vt-link/backend/internal/domain/model"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockCampaignRepository is an autogenerated mock type for the CampaignRepository type
type MockCampaignRepository struct {
	mock.Mock
}

type MockCampaignRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCampaignRepository) EXPECT() *MockCampaignRepository_Expecter {
	return &MockCampaignRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, campaign
func (_m *MockCampaignRepository) Create(ctx context.Context, campaign *model.Campaign) error {
	ret := _m.Called(ctx, campaign)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Campaign) error); ok {
		r0 = rf(ctx, campaign)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCampaignRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCampaignRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - campaign *model.Campaign
func (_e *MockCampaignRepository_Expecter) Create(ctx interface{}, campaign interface{}) *MockCampaignRepository_Create_Call {
	return &MockCampaignRepository_Create_Call{Call: _e.mock.On("Create", ctx, campaign)}
}

func (_c *MockCampaignRepository_Create_Call) Run(run func(ctx context.Context, campaign *model.Campaign)) *MockCampaignRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Campaign))
	})
	return _c
}

func (_c *MockCampaignRepository_Create_Call) Return(_a0 error) *MockCampaignRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCampaignRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Campaign) error) *MockCampaignRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCampaignRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Campaign, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Campaign, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Campaign); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCampaignRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCampaignRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCampaignRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCampaignRepository_FindByID_Call {
	return &MockCampaignRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCampaignRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCampaignRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCampaignRepository_FindByID_Call) Return(_a0 *model.Campaign, _a1 error) *MockCampaignRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCampaignRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Campaign, error)) *MockCampaignRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindScheduledCampaigns provides a mock function with given fields: ctx, until, limit
func (_m *MockCampaignRepository) FindScheduledCampaigns(ctx context.Context, until time.Time, limit int) ([]*model.Campaign, error) {
	ret := _m.Called(ctx, until, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindScheduledCampaigns")
	}

	var r0 []*model.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]*model.Campaign, error)); ok {
		return rf(ctx, until, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []*model.Campaign); ok {
		r0 = rf(ctx, until, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, until, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCampaignRepository_FindScheduledCampaigns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindScheduledCampaigns'
type MockCampaignRepository_FindScheduledCampaigns_Call struct {
	*mock.Call
}

// FindScheduledCampaigns is a helper method to define mock.On call
//   - ctx context.Context
//   - until time.Time
//   - limit int
func (_e *MockCampaignRepository_Expecter) FindScheduledCampaigns(ctx interface{}, until interface{}, limit interface{}) *MockCampaignRepository_FindScheduledCampaigns_Call {
	return &MockCampaignRepository_FindScheduledCampaigns_Call{Call: _e.mock.On("FindScheduledCampaigns", ctx, until, limit)}
}

func (_c *MockCampaignRepository_FindScheduledCampaigns_Call) Run(run func(ctx context.Context, until time.Time, limit int)) *MockCampaignRepository_FindScheduledCampaigns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int))
	})
	return _c
}

func (_c *MockCampaignRepository_FindScheduledCampaigns_Call) Return(_a0 []*model.Campaign, _a1 error) *MockCampaignRepository_FindScheduledCampaigns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCampaignRepository_FindScheduledCampaigns_Call) RunAndReturn(run func(context.Context, time.Time, int) ([]*model.Campaign, error)) *MockCampaignRepository_FindScheduledCampaigns_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *MockCampaignRepository) List(ctx context.Context, limit int, offset int) ([]*model.Campaign, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*model.Campaign, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*model.Campaign); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCampaignRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCampaignRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockCampaignRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockCampaignRepository_List_Call {
	return &MockCampaignRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockCampaignRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockCampaignRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockCampaignRepository_List_Call) Return(_a0 []*model.Campaign, _a1 error) *MockCampaignRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCampaignRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*model.Campaign, error)) *MockCampaignRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, campaign
func (_m *MockCampaignRepository) Update(ctx context.Context, campaign *model.Campaign) error {
	ret := _m.Called(ctx, campaign)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Campaign) error); ok {
		r0 = rf(ctx, campaign)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCampaignRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCampaignRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - campaign *model.Campaign
func (_e *MockCampaignRepository_Expecter) Update(ctx interface{}, campaign interface{}) *MockCampaignRepository_Update_Call {
	return &MockCampaignRepository_Update_Call{Call: _e.mock.On("Update", ctx, campaign)}
}

func (_c *MockCampaignRepository_Update_Call) Run(run func(ctx context.Context, campaign *model.Campaign)) *MockCampaignRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Campaign))
	})
	return _c
}

func (_c *MockCampaignRepository_Update_Call) Return(_a0 error) *MockCampaignRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCampaignRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Campaign) error) *MockCampaignRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCampaignRepository creates a new instance of MockCampaignRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCampaignRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCampaignRepository {
	mock := &MockCampaignRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
