// Code generated by MockGen. DO NOT EDIT.
// Source: line_replier.go
//
// Generated by this command:
//
//	mockgen -source=line_replier.go -destination=mocks/mock_line_replier.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLineReplier is a mock of LineReplier interface.
type MockLineReplier struct {
	ctrl     *gomock.Controller
	recorder *MockLineReplierMockRecorder
	isgomock struct{}
}

// MockLineReplierMockRecorder is the mock recorder for MockLineReplier.
type MockLineReplierMockRecorder struct {
	mock *MockLineReplier
}

// NewMockLineReplier creates a new mock instance.
func NewMockLineReplier(ctrl *gomock.Controller) *MockLineReplier {
	mock := &MockLineReplier{ctrl: ctrl}
	mock.recorder = &MockLineReplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLineReplier) EXPECT() *MockLineReplierMockRecorder {
	return m.recorder
}

// Reply mocks base method.
func (m *MockLineReplier) Reply(ctx context.Context, replyToken, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reply", ctx, replyToken, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reply indicates an expected call of Reply.
func (mr *MockLineReplierMockRecorder) Reply(ctx, replyToken, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reply", reflect.TypeOf((*MockLineReplier)(nil).Reply), ctx, replyToken, text)
}
