// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	model "vt-link/backend/internal/domain/model"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockMessageRepository is an autogenerated mock type for the MessageRepository type
type MockMessageRepository struct {
	mock.Mock
}

type MockMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepository) EXPECT() *MockMessageRepository_Expecter {
	return &MockMessageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, message
func (_m *MockMessageRepository) Create(ctx context.Context, message *model.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMessageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - message *model.Message
func (_e *MockMessageRepository_Expecter) Create(ctx interface{}, message interface{}) *MockMessageRepository_Create_Call {
	return &MockMessageRepository_Create_Call{Call: _e.mock.On("Create", ctx, message)}
}

func (_c *MockMessageRepository_Create_Call) Run(run func(ctx context.Context, message *model.Message)) *MockMessageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Message))
	})
	return _c
}

func (_c *MockMessageRepository_Create_Call) Return(_a0 error) *MockMessageRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Message) error) *MockMessageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockMessageRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Message, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Message, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Message); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockMessageRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMessageRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockMessageRepository_FindByID_Call {
	return &MockMessageRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockMessageRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMessageRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMessageRepository_FindByID_Call) Return(_a0 *model.Message, _a1 error) *MockMessageRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Message, error)) *MockMessageRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindScheduledMessages provides a mock function with given fields: ctx, until, limit
func (_m *MockMessageRepository) FindScheduledMessages(ctx context.Context, until time.Time, limit int) ([]*model.Message, error) {
	ret := _m.Called(ctx, until, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindScheduledMessages")
	}

	var r0 []*model.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]*model.Message, error)); ok {
		return rf(ctx, until, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []*model.Message); ok {
		r0 = rf(ctx, until, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, until, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepository_FindScheduledMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindScheduledMessages'
type MockMessageRepository_FindScheduledMessages_Call struct {
	*mock.Call
}

// FindScheduledMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - until time.Time
//   - limit int
func (_e *MockMessageRepository_Expecter) FindScheduledMessages(ctx interface{}, until interface{}, limit interface{}) *MockMessageRepository_FindScheduledMessages_Call {
	return &MockMessageRepository_FindScheduledMessages_Call{Call: _e.mock.On("FindScheduledMessages", ctx, until, limit)}
}

func (_c *MockMessageRepository_FindScheduledMessages_Call) Run(run func(ctx context.Context, until time.Time, limit int)) *MockMessageRepository_FindScheduledMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int))
	})
	return _c
}

func (_c *MockMessageRepository_FindScheduledMessages_Call) Return(_a0 []*model.Message, _a1 error) *MockMessageRepository_FindScheduledMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepository_FindScheduledMessages_Call) RunAndReturn(run func(context.Context, time.Time, int) ([]*model.Message, error)) *MockMessageRepository_FindScheduledMessages_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *MockMessageRepository) List(ctx context.Context, limit int, offset int) ([]*model.Message, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*model.Message, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*model.Message); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMessageRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockMessageRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockMessageRepository_List_Call {
	return &MockMessageRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockMessageRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockMessageRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockMessageRepository_List_Call) Return(_a0 []*model.Message, _a1 error) *MockMessageRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*model.Message, error)) *MockMessageRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockMessageRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMessageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMessageRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockMessageRepository_Delete_Call {
	return &MockMessageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockMessageRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMessageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMessageRepository_Delete_Call) Return(_a0 error) *MockMessageRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockMessageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, message
func (_m *MockMessageRepository) Update(ctx context.Context, message *model.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMessageRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - message *model.Message
func (_e *MockMessageRepository_Expecter) Update(ctx interface{}, message interface{}) *MockMessageRepository_Update_Call {
	return &MockMessageRepository_Update_Call{Call: _e.mock.On("Update", ctx, message)}
}

func (_c *MockMessageRepository_Update_Call) Run(run func(ctx context.Context, message *model.Message)) *MockMessageRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Message))
	})
	return _c
}

func (_c *MockMessageRepository_Update_Call) Return(_a0 error) *MockMessageRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Message) error) *MockMessageRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageRepository creates a new instance of MockMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepository {
	mock := &MockMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
