// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	model "vt-link/backend/internal/domain/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAutoReplyRuleRepository is an autogenerated mock type for the AutoReplyRuleRepository type
type MockAutoReplyRuleRepository struct {
	mock.Mock
}

type MockAutoReplyRuleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAutoReplyRuleRepository) EXPECT() *MockAutoReplyRuleRepository_Expecter {
	return &MockAutoReplyRuleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, rule
func (_m *MockAutoReplyRuleRepository) Create(ctx context.Context, rule *model.AutoReplyRule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AutoReplyRule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAutoReplyRuleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAutoReplyRuleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *model.AutoReplyRule
func (_e *MockAutoReplyRuleRepository_Expecter) Create(ctx interface{}, rule interface{}) *MockAutoReplyRuleRepository_Create_Call {
	return &MockAutoReplyRuleRepository_Create_Call{Call: _e.mock.On("Create", ctx, rule)}
}

func (_c *MockAutoReplyRuleRepository_Create_Call) Run(run func(ctx context.Context, rule *model.AutoReplyRule)) *MockAutoReplyRuleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AutoReplyRule))
	})
	return _c
}

func (_c *MockAutoReplyRuleRepository_Create_Call) Return(_a0 error) *MockAutoReplyRuleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAutoReplyRuleRepository_Create_Call) RunAndReturn(run func(context.Context, *model.AutoReplyRule) error) *MockAutoReplyRuleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockAutoReplyRuleRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.AutoReplyRule, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.AutoReplyRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.AutoReplyRule, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.AutoReplyRule); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AutoReplyRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAutoReplyRuleRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAutoReplyRuleRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAutoReplyRuleRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockAutoReplyRuleRepository_FindByID_Call {
	return &MockAutoReplyRuleRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockAutoReplyRuleRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAutoReplyRuleRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAutoReplyRuleRepository_FindByID_Call) Return(_a0 *model.AutoReplyRule, _a1 error) *MockAutoReplyRuleRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAutoReplyRuleRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.AutoReplyRule, error)) *MockAutoReplyRuleRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAutoReplyRuleRepository) FindByUserID(ctx context.Context, userID uuid.UUID) ([]*model.AutoReplyRule, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*model.AutoReplyRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.AutoReplyRule, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.AutoReplyRule); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AutoReplyRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAutoReplyRuleRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockAutoReplyRuleRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAutoReplyRuleRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockAutoReplyRuleRepository_FindByUserID_Call {
	return &MockAutoReplyRuleRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockAutoReplyRuleRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAutoReplyRuleRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAutoReplyRuleRepository_FindByUserID_Call) Return(_a0 []*model.AutoReplyRule, _a1 error) *MockAutoReplyRuleRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAutoReplyRuleRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.AutoReplyRule, error)) *MockAutoReplyRuleRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, rule
func (_m *MockAutoReplyRuleRepository) Update(ctx context.Context, rule *model.AutoReplyRule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AutoReplyRule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAutoReplyRuleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAutoReplyRuleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *model.AutoReplyRule
func (_e *MockAutoReplyRuleRepository_Expecter) Update(ctx interface{}, rule interface{}) *MockAutoReplyRuleRepository_Update_Call {
	return &MockAutoReplyRuleRepository_Update_Call{Call: _e.mock.On("Update", ctx, rule)}
}

func (_c *MockAutoReplyRuleRepository_Update_Call) Run(run func(ctx context.Context, rule *model.AutoReplyRule)) *MockAutoReplyRuleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AutoReplyRule))
	})
	return _c
}

func (_c *MockAutoReplyRuleRepository_Update_Call) Return(_a0 error) *MockAutoReplyRuleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAutoReplyRuleRepository_Update_Call) RunAndReturn(run func(context.Context, *model.AutoReplyRule) error) *MockAutoReplyRuleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAutoReplyRuleRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAutoReplyRuleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAutoReplyRuleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAutoReplyRuleRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAutoReplyRuleRepository_Delete_Call {
	return &MockAutoReplyRuleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAutoReplyRuleRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAutoReplyRuleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAutoReplyRuleRepository_Delete_Call) Return(_a0 error) *MockAutoReplyRuleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAutoReplyRuleRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAutoReplyRuleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAutoReplyRuleRepository creates a new instance of MockAutoReplyRuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAutoReplyRuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAutoReplyRuleRepository {
	mock := &MockAutoReplyRuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
