// Code generated by MockGen. DO NOT EDIT.
// Source: pusher.go
//
// Generated by this command:
//
//	mockgen -source=pusher.go -destination=mocks/mock_pusher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPusher is a mock of Pusher interface.
type MockPusher struct {
	ctrl     *gomock.Controller
	recorder *MockPusherMockRecorder
	isgomock struct{}
}

// MockPusherMockRecorder is the mock recorder for MockPusher.
type MockPusherMockRecorder struct {
	mock *MockPusher
}

// NewMockPusher creates a new mock instance.
func NewMockPusher(ctrl *gomock.Controller) *MockPusher {
	mock := &MockPusher{ctrl: ctrl}
	mock.recorder = &MockPusherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPusher) EXPECT() *MockPusherMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockPusher) Broadcast(ctx context.Context, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broadcast", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockPusherMockRecorder) Broadcast(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockPusher)(nil).Broadcast), ctx, message)
}

// MulticastByAudience mocks base method.
func (m *MockPusher) MulticastByAudience(ctx context.Context, audienceIDs []string, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MulticastByAudience", ctx, audienceIDs, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// MulticastByAudience indicates an expected call of MulticastByAudience.
func (mr *MockPusherMockRecorder) MulticastByAudience(ctx, audienceIDs, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MulticastByAudience", reflect.TypeOf((*MockPusher)(nil).MulticastByAudience), ctx, audienceIDs, message)
}

// PushMessage mocks base method.
func (m *MockPusher) PushMessage(ctx context.Context, title, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushMessage", ctx, title, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushMessage indicates an expected call of PushMessage.
func (mr *MockPusherMockRecorder) PushMessage(ctx, title, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushMessage", reflect.TypeOf((*MockPusher)(nil).PushMessage), ctx, title, body)
}

// PushText mocks base method.
func (m *MockPusher) PushText(ctx context.Context, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushText", ctx, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushText indicates an expected call of PushText.
func (mr *MockPusherMockRecorder) PushText(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushText", reflect.TypeOf((*MockPusher)(nil).PushText), ctx, text)
}

// PushWithRetry mocks base method.
func (m *MockPusher) PushWithRetry(ctx context.Context, message string, maxRetries int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushWithRetry", ctx, message, maxRetries)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushWithRetry indicates an expected call of PushWithRetry.
func (mr *MockPusherMockRecorder) PushWithRetry(ctx, message, maxRetries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushWithRetry", reflect.TypeOf((*MockPusher)(nil).PushWithRetry), ctx, message, maxRetries)
}
