// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	model "vt-link/backend/internal/domain/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRichMenuRepository is an autogenerated mock type for the RichMenuRepository type
type MockRichMenuRepository struct {
	mock.Mock
}

type MockRichMenuRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRichMenuRepository) EXPECT() *MockRichMenuRepository_Expecter {
	return &MockRichMenuRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, menu
func (_m *MockRichMenuRepository) Create(ctx context.Context, menu *model.RichMenu) error {
	ret := _m.Called(ctx, menu)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RichMenu) error); ok {
		r0 = rf(ctx, menu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRichMenuRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRichMenuRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - menu *model.RichMenu
func (_e *MockRichMenuRepository_Expecter) Create(ctx interface{}, menu interface{}) *MockRichMenuRepository_Create_Call {
	return &MockRichMenuRepository_Create_Call{Call: _e.mock.On("Create", ctx, menu)}
}

func (_c *MockRichMenuRepository_Create_Call) Run(run func(ctx context.Context, menu *model.RichMenu)) *MockRichMenuRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.RichMenu))
	})
	return _c
}

func (_c *MockRichMenuRepository_Create_Call) Return(_a0 error) *MockRichMenuRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRichMenuRepository_Create_Call) RunAndReturn(run func(context.Context, *model.RichMenu) error) *MockRichMenuRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRichMenuRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.RichMenu, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.RichMenu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.RichMenu, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.RichMenu); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RichMenu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRichMenuRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRichMenuRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRichMenuRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRichMenuRepository_FindByID_Call {
	return &MockRichMenuRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRichMenuRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRichMenuRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRichMenuRepository_FindByID_Call) Return(_a0 *model.RichMenu, _a1 error) *MockRichMenuRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRichMenuRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.RichMenu, error)) *MockRichMenuRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRichMenuRepository) FindByUserID(ctx context.Context, userID uuid.UUID) (*model.RichMenu, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *model.RichMenu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.RichMenu, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.RichMenu); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RichMenu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRichMenuRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockRichMenuRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRichMenuRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockRichMenuRepository_FindByUserID_Call {
	return &MockRichMenuRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockRichMenuRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRichMenuRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRichMenuRepository_FindByUserID_Call) Return(_a0 *model.RichMenu, _a1 error) *MockRichMenuRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRichMenuRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.RichMenu, error)) *MockRichMenuRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, menu
func (_m *MockRichMenuRepository) Update(ctx context.Context, menu *model.RichMenu) error {
	ret := _m.Called(ctx, menu)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RichMenu) error); ok {
		r0 = rf(ctx, menu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRichMenuRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRichMenuRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - menu *model.RichMenu
func (_e *MockRichMenuRepository_Expecter) Update(ctx interface{}, menu interface{}) *MockRichMenuRepository_Update_Call {
	return &MockRichMenuRepository_Update_Call{Call: _e.mock.On("Update", ctx, menu)}
}

func (_c *MockRichMenuRepository_Update_Call) Run(run func(ctx context.Context, menu *model.RichMenu)) *MockRichMenuRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.RichMenu))
	})
	return _c
}

func (_c *MockRichMenuRepository_Update_Call) Return(_a0 error) *MockRichMenuRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRichMenuRepository_Update_Call) RunAndReturn(run func(context.Context, *model.RichMenu) error) *MockRichMenuRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRichMenuRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRichMenuRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRichMenuRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRichMenuRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRichMenuRepository_Delete_Call {
	return &MockRichMenuRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRichMenuRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRichMenuRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRichMenuRepository_Delete_Call) Return(_a0 error) *MockRichMenuRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRichMenuRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRichMenuRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// SetActive provides a mock function with given fields: ctx, id, isActive
func (_m *MockRichMenuRepository) SetActive(ctx context.Context, id uuid.UUID, isActive bool) error {
	ret := _m.Called(ctx, id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRichMenuRepository_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type MockRichMenuRepository_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - isActive bool
func (_e *MockRichMenuRepository_Expecter) SetActive(ctx interface{}, id interface{}, isActive interface{}) *MockRichMenuRepository_SetActive_Call {
	return &MockRichMenuRepository_SetActive_Call{Call: _e.mock.On("SetActive", ctx, id, isActive)}
}

func (_c *MockRichMenuRepository_SetActive_Call) Run(run func(ctx context.Context, id uuid.UUID, isActive bool)) *MockRichMenuRepository_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockRichMenuRepository_SetActive_Call) Return(_a0 error) *MockRichMenuRepository_SetActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRichMenuRepository_SetActive_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockRichMenuRepository_SetActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRichMenuRepository creates a new instance of MockRichMenuRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRichMenuRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRichMenuRepository {
	mock := &MockRichMenuRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
