// Code generated by MockGen. DO NOT EDIT.
// Source: auto_reply_rule_repo.go
//
// Generated by this command:
//
//	mockgen -source=auto_reply_rule_repo.go -destination=mocks/mock_auto_reply_rule_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "vt-link/backend/internal/domain/model"
	repository "vt-link/backend/internal/domain/repository"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAutoReplyRuleRepository is a mock of AutoReplyRuleRepository interface.
type MockAutoReplyRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAutoReplyRuleRepositoryMockRecorder
	isgomock struct{}
}

// MockAutoReplyRuleRepositoryMockRecorder is the mock recorder for MockAutoReplyRuleRepository.
type MockAutoReplyRuleRepositoryMockRecorder struct {
	mock *MockAutoReplyRuleRepository
}

// NewMockAutoReplyRuleRepository creates a new mock instance.
func NewMockAutoReplyRuleRepository(ctrl *gomock.Controller) *MockAutoReplyRuleRepository {
	mock := &MockAutoReplyRuleRepository{ctrl: ctrl}
	mock.recorder = &MockAutoReplyRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutoReplyRuleRepository) EXPECT() *MockAutoReplyRuleRepositoryMockRecorder {
	return m.recorder
}

// BulkUpdateEnabled mocks base method.
func (m *MockAutoReplyRuleRepository) BulkUpdateEnabled(ctx context.Context, items []repository.BulkUpdateItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateEnabled", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateEnabled indicates an expected call of BulkUpdateEnabled.
func (mr *MockAutoReplyRuleRepositoryMockRecorder) BulkUpdateEnabled(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateEnabled", reflect.TypeOf((*MockAutoReplyRuleRepository)(nil).BulkUpdateEnabled), ctx, items)
}

// Create mocks base method.
func (m *MockAutoReplyRuleRepository) Create(ctx context.Context, rule *model.AutoReplyRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAutoReplyRuleRepositoryMockRecorder) Create(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAutoReplyRuleRepository)(nil).Create), ctx, rule)
}

// Delete mocks base method.
func (m *MockAutoReplyRuleRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAutoReplyRuleRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAutoReplyRuleRepository)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockAutoReplyRuleRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.AutoReplyRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.AutoReplyRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAutoReplyRuleRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAutoReplyRuleRepository)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockAutoReplyRuleRepository) FindByUserID(ctx context.Context, userID uuid.UUID) ([]*model.AutoReplyRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.AutoReplyRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockAutoReplyRuleRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockAutoReplyRuleRepository)(nil).FindByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockAutoReplyRuleRepository) Update(ctx context.Context, rule *model.AutoReplyRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAutoReplyRuleRepositoryMockRecorder) Update(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAutoReplyRuleRepository)(nil).Update), ctx, rule)
}
