// Code generated by MockGen. DO NOT EDIT.
// Source: user_settings_repo.go
//
// Generated by this command:
//
//	mockgen -source=user_settings_repo.go -destination=mocks/mock_user_settings_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "vt-link/backend/internal/domain/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserSettingsRepository is a mock of UserSettingsRepository interface.
type MockUserSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockUserSettingsRepositoryMockRecorder is the mock recorder for MockUserSettingsRepository.
type MockUserSettingsRepositoryMockRecorder struct {
	mock *MockUserSettingsRepository
}

// NewMockUserSettingsRepository creates a new mock instance.
func NewMockUserSettingsRepository(ctrl *gomock.Controller) *MockUserSettingsRepository {
	mock := &MockUserSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockUserSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSettingsRepository) EXPECT() *MockUserSettingsRepositoryMockRecorder {
	return m.recorder
}

// FindByUserID mocks base method.
func (m *MockUserSettingsRepository) FindByUserID(ctx context.Context, userID uuid.UUID) (*model.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockUserSettingsRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockUserSettingsRepository)(nil).FindByUserID), ctx, userID)
}

// Upsert mocks base method.
func (m *MockUserSettingsRepository) Upsert(ctx context.Context, settings *model.UserSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockUserSettingsRepositoryMockRecorder) Upsert(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockUserSettingsRepository)(nil).Upsert), ctx, settings)
}
