// Code generated by MockGen. DO NOT EDIT.
// Source: rich_menu_repo.go
//
// Generated by this command:
//
//	mockgen -source=rich_menu_repo.go -destination=mocks/mock_rich_menu_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "vt-link/backend/internal/domain/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRichMenuRepository is a mock of RichMenuRepository interface.
type MockRichMenuRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRichMenuRepositoryMockRecorder
	isgomock struct{}
}

// MockRichMenuRepositoryMockRecorder is the mock recorder for MockRichMenuRepository.
type MockRichMenuRepositoryMockRecorder struct {
	mock *MockRichMenuRepository
}

// NewMockRichMenuRepository creates a new mock instance.
func NewMockRichMenuRepository(ctrl *gomock.Controller) *MockRichMenuRepository {
	mock := &MockRichMenuRepository{ctrl: ctrl}
	mock.recorder = &MockRichMenuRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRichMenuRepository) EXPECT() *MockRichMenuRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRichMenuRepository) Create(ctx context.Context, menu *model.RichMenu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, menu)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRichMenuRepositoryMockRecorder) Create(ctx, menu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRichMenuRepository)(nil).Create), ctx, menu)
}

// Delete mocks base method.
func (m *MockRichMenuRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRichMenuRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRichMenuRepository)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockRichMenuRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.RichMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.RichMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRichMenuRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRichMenuRepository)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockRichMenuRepository) FindByUserID(ctx context.Context, userID uuid.UUID) (*model.RichMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.RichMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockRichMenuRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockRichMenuRepository)(nil).FindByUserID), ctx, userID)
}

// SetActive mocks base method.
func (m *MockRichMenuRepository) SetActive(ctx context.Context, id uuid.UUID, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, id, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockRichMenuRepositoryMockRecorder) SetActive(ctx, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockRichMenuRepository)(nil).SetActive), ctx, id, isActive)
}

// Update mocks base method.
func (m *MockRichMenuRepository) Update(ctx context.Context, menu *model.RichMenu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, menu)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRichMenuRepositoryMockRecorder) Update(ctx, menu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRichMenuRepository)(nil).Update), ctx, menu)
}
