// Code generated by MockGen. DO NOT EDIT.
// Source: fan_repo.go
//
// Generated by this command:
//
//	mockgen -source=fan_repo.go -destination=mocks/mock_fan_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "vt-link/backend/internal/domain/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFanRepository is a mock of FanRepository interface.
type MockFanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFanRepositoryMockRecorder
	isgomock struct{}
}

// MockFanRepositoryMockRecorder is the mock recorder for MockFanRepository.
type MockFanRepositoryMockRecorder struct {
	mock *MockFanRepository
}

// NewMockFanRepository creates a new mock instance.
func NewMockFanRepository(ctrl *gomock.Controller) *MockFanRepository {
	mock := &MockFanRepository{ctrl: ctrl}
	mock.recorder = &MockFanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFanRepository) EXPECT() *MockFanRepositoryMockRecorder {
	return m.recorder
}

// CountActiveByUserID mocks base method.
func (m *MockFanRepository) CountActiveByUserID(ctx context.Context, userID uuid.UUID, days int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByUserID", ctx, userID, days)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByUserID indicates an expected call of CountActiveByUserID.
func (mr *MockFanRepositoryMockRecorder) CountActiveByUserID(ctx, userID, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByUserID", reflect.TypeOf((*MockFanRepository)(nil).CountActiveByUserID), ctx, userID, days)
}

// CountByUserID mocks base method.
func (m *MockFanRepository) CountByUserID(ctx context.Context, userID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockFanRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockFanRepository)(nil).CountByUserID), ctx, userID)
}

// CountNewByUserID mocks base method.
func (m *MockFanRepository) CountNewByUserID(ctx context.Context, userID uuid.UUID, days int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountNewByUserID", ctx, userID, days)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountNewByUserID indicates an expected call of CountNewByUserID.
func (mr *MockFanRepositoryMockRecorder) CountNewByUserID(ctx, userID, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountNewByUserID", reflect.TypeOf((*MockFanRepository)(nil).CountNewByUserID), ctx, userID, days)
}

// Create mocks base method.
func (m *MockFanRepository) Create(ctx context.Context, fan *model.Fan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, fan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFanRepositoryMockRecorder) Create(ctx, fan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFanRepository)(nil).Create), ctx, fan)
}

// Delete mocks base method.
func (m *MockFanRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFanRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFanRepository)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockFanRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Fan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Fan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFanRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFanRepository)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockFanRepository) FindByUserID(ctx context.Context, userID uuid.UUID, limit, offset int) ([]*model.Fan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*model.Fan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockFanRepositoryMockRecorder) FindByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockFanRepository)(nil).FindByUserID), ctx, userID, limit, offset)
}

// FindByUserIDAndLineUserID mocks base method.
func (m *MockFanRepository) FindByUserIDAndLineUserID(ctx context.Context, userID uuid.UUID, lineUserID string) (*model.Fan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndLineUserID", ctx, userID, lineUserID)
	ret0, _ := ret[0].(*model.Fan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndLineUserID indicates an expected call of FindByUserIDAndLineUserID.
func (mr *MockFanRepositoryMockRecorder) FindByUserIDAndLineUserID(ctx, userID, lineUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndLineUserID", reflect.TypeOf((*MockFanRepository)(nil).FindByUserIDAndLineUserID), ctx, userID, lineUserID)
}

// Update mocks base method.
func (m *MockFanRepository) Update(ctx context.Context, fan *model.Fan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, fan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFanRepositoryMockRecorder) Update(ctx, fan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFanRepository)(nil).Update), ctx, fan)
}
