// Code generated by MockGen. DO NOT EDIT.
// Source: message_history_repo.go
//
// Generated by this command:
//
//	mockgen -source=message_history_repo.go -destination=mocks/mock_message_history_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "vt-link/backend/internal/domain/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageHistoryRepository is a mock of MessageHistoryRepository interface.
type MockMessageHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageHistoryRepositoryMockRecorder is the mock recorder for MockMessageHistoryRepository.
type MockMessageHistoryRepositoryMockRecorder struct {
	mock *MockMessageHistoryRepository
}

// NewMockMessageHistoryRepository creates a new mock instance.
func NewMockMessageHistoryRepository(ctrl *gomock.Controller) *MockMessageHistoryRepository {
	mock := &MockMessageHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockMessageHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageHistoryRepository) EXPECT() *MockMessageHistoryRepositoryMockRecorder {
	return m.recorder
}

// CountByUserID mocks base method.
func (m *MockMessageHistoryRepository) CountByUserID(ctx context.Context, userID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockMessageHistoryRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockMessageHistoryRepository)(nil).CountByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockMessageHistoryRepository) Create(ctx context.Context, history *model.MessageHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMessageHistoryRepositoryMockRecorder) Create(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageHistoryRepository)(nil).Create), ctx, history)
}

// Delete mocks base method.
func (m *MockMessageHistoryRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMessageHistoryRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMessageHistoryRepository)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockMessageHistoryRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.MessageHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.MessageHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMessageHistoryRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMessageHistoryRepository)(nil).FindByID), ctx, id)
}

// GetLastSentDateByUserID mocks base method.
func (m *MockMessageHistoryRepository) GetLastSentDateByUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastSentDateByUserID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastSentDateByUserID indicates an expected call of GetLastSentDateByUserID.
func (mr *MockMessageHistoryRepositoryMockRecorder) GetLastSentDateByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastSentDateByUserID", reflect.TypeOf((*MockMessageHistoryRepository)(nil).GetLastSentDateByUserID), ctx, userID)
}

// ListByUserID mocks base method.
func (m *MockMessageHistoryRepository) ListByUserID(ctx context.Context, userID uuid.UUID, limit, offset int) ([]*model.MessageHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*model.MessageHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockMessageHistoryRepositoryMockRecorder) ListByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockMessageHistoryRepository)(nil).ListByUserID), ctx, userID, limit, offset)
}

// SumRecipientsByUserID mocks base method.
func (m *MockMessageHistoryRepository) SumRecipientsByUserID(ctx context.Context, userID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumRecipientsByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumRecipientsByUserID indicates an expected call of SumRecipientsByUserID.
func (mr *MockMessageHistoryRepositoryMockRecorder) SumRecipientsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumRecipientsByUserID", reflect.TypeOf((*MockMessageHistoryRepository)(nil).SumRecipientsByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockMessageHistoryRepository) Update(ctx context.Context, history *model.MessageHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMessageHistoryRepositoryMockRecorder) Update(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMessageHistoryRepository)(nil).Update), ctx, history)
}
